name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/markdown.yml
      - '**/*.md'

jobs:
  markdownlint:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: DavidAnson/markdownlint-cli2-action@a23dae216ce3fee4db69da41fed90d2a4af801cf
        with:
          globs: |
            **/*.md
            !target/**
